apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: frontend
spec:
  dependsOn:
    - name: common
    - name: backend
  interval: 5m
  path: "./deploy/webapp/frontend/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: webapp
  validation: server
  healthChecks:
    - kind: Deployment
      name: frontend
      namespace: webapp
  timeout: 2m
