apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kustomizationb
  namespace: namespace2
spec:
  dependsOn:
    - name: kustomizationa
      namespace: namespace1
  interval: 5m
  path: "./deploy/webapp/backend/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: webapp
    namespace: webapp
  validation: server
  healthChecks:
    - kind: Deployment
      name: backend
      namespace: webapp
  timeout: 2m
