apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kustomizationc
spec:
  dependsOn:
    - name: kustomizationa
      namespace: namespace1
  interval: 5m
  path: "./deploy/webapp/frontend/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: webapp
  validation: server
  healthChecks:
    - kind: Deployment
      name: frontend
      namespace: webapp
  timeout: 2m
