apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization1
  namespace: namespace3
spec:
  interval: 5m
  path: "./deploy/webapp/common/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: webapp
    namespace: webapp
  validation: client
