apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kustomizatione
  namespace: namespace1
spec:
  dependsOn:
    - name: kustomizationa
      namespace: namespace1
    - name: kustomization1
      namespace: namespace3
  interval: 5m
  path: "./deploy/webapp/backend/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: webapp
  validation: server
  healthChecks:
    - kind: Deployment
      name: backend
      namespace: webapp
  timeout: 2m
